language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rish_goel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rish_goel/docker-react npm run test